name: File operations in github
  
on: workflow_dispatch
 
jobs:
    files:
        runs-on: ubuntu-latest
        steps:
            - name: create a file
              run: echo "hi suneetha"> devops4.txt

            - name: Display the content of file
              run: cat devops4.txt
              
            - name: display the date
              run: date
              
            - name: display file and dir
              run: ls -lrth
              
            - name: display the present location
              run: pwd 